### ISSUE TITLE
TODO: renders 2x/frame ...

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#14]
In LinePlot.js and ScatterPlot.js:

```js
// TODO https://github.com/phetsims/bamboo/issues/13 renders 2x/frame if a point is added and the chart scrolls
```

Assigning to @samreid for discussion.

**Comment by samreid** [comment]
Since the data sets are now `Vector2[]`, clients could use the following pattern to only `update` once per frame, even if adding a data point and scrolling the chart:

```js
dataSet.push(new Vector2(x,y)); // no update
chartTransform.setModelXRange(10,20); // calls update
```

Does that seem reasonable? In the commit, I added documentation to indicate that is possible.  @pixelzoom does this seem OK to you?

**Comment by pixelzoom** [comment]
Sounds reasonable to me. Minor typo in doc fixed in the above commit.  Closing.
