### ISSUE TITLE
Canvas context should be saved and restored

### ISSUE THREAD

**Issue by samreid** [phetsims/bamboo#44]
From https://github.com/phetsims/circuit-construction-kit-common/issues/728#issuecomment-909578963, we discovered that canvas painters don't save and restore their state.  @jonathanolson said it's best to factor this out so a painter is not responsible for it, and cannot forget it.  It is well-optimized in browsers.

**Comment by samreid** [comment]
Fixed in the commit.  @pixelzoom can you please review?  I also searched fourier for any save/restore that may no longer be necessary, but I didn't see any.

**Comment by pixelzoom** [comment]
It might be better to have @jonathanolson review this, since I'm unfamiliar with the optimization that you're trying to address.

But I do have a question https://github.com/phetsims/bamboo/commit/c5d1c499ece95d513d08be680e0433d23ac06a03.  ChartCanvasNode `paintCanvas` now has this implementation:

```js
  paintCanvas( context ) {
    this.painters.forEach( painter => {
      if ( painter.visible ) {
        context.save();
        painter.paintCanvas( context );
        context.restore();
      }
    } );
  }
```

If there are N painters, you're calling `context.save` and `context.restore` N times.  Is that necessary?

**Comment by samreid** [comment]
The save and restore for each paintContext is intentional, so that we are guaranteed that a fill, transform, etc from one painter won't leak into another painter.  @jonathanolson would you like to review?  It's pretty similar to what we discussed on the call.

**Comment by samreid** [comment]
Thanks, I added a comment.

**Comment by jonathanolson** [comment]
Looks good to me!

**Comment by samreid** [comment]
Thanks, closing.
