### ISSUE TITLE
Implement a NumberLinePlot to consolidate number line usages/creation

### ISSUE THREAD

**Issue by marlitas** [phetsims/bamboo#56]
While working on Build a Nucleus, @Luisav1 and I were looking for a common code component for a number line. We discovered many sim specific usages of a number line, but no common component. Here are some images of number lines found across some sims, this is not a comprehensive list.

number-line-distance:
![Screenshot 2022-12-14 at 11 13 28 AM](https://user-images.githubusercontent.com/42476338/207692991-ec6ffd54-4053-4dc9-ad39-a586eaeee77b.png)

number-line-integers:
![Screenshot 2022-12-14 at 11 13 57 AM](https://user-images.githubusercontent.com/42476338/207693035-13f6a3fa-2b64-4cca-96c0-a3d83812560f.png)

build-a-nucleus:
![Screenshot 2022-12-14 at 11 14 51 AM](https://user-images.githubusercontent.com/42476338/207693071-174906bf-b0ce-43ed-b6e4-32e42593c134.png)

center-and-variability:
![Screenshot 2022-12-14 at 11 14 30 AM](https://user-images.githubusercontent.com/42476338/207693161-acdbe687-af31-4343-9d10-1e7459804dcc.png)

fractions-equality:
![Screenshot 2022-12-14 at 11 18 54 AM](https://user-images.githubusercontent.com/42476338/207693251-59b86340-53db-401e-ab52-5f4656533fa9.png)

number-compare:
![Screenshot 2022-12-14 at 11 22 57 AM](https://user-images.githubusercontent.com/42476338/207694150-aa3077ce-ea45-47b5-903b-d3d27d6fc0ab.png)

**Comment by veillette** [comment]
I think the philosophy of bamboo is to design small but reusable components to create charts/graphs/plots.
The power of bamboo is in its flexibility, where one can pick particular components of Bamboo in order to achieve the desired effect. For instance, Bamboo has TickMarkSet, TickMarkLabel , AxisLine and AxisArrowNode which can be used to create a NumberLine. 
I'll note that Bamboo is a relatively new library so there are not a lot of usages in our code base yet.

**Comment by marlitas** [comment]
After talking through the bamboo options that exist, and working through some of this with @veillette on Build a Nucleus, it seems to me this is currently unnecessary. Closing.
